import type { Metadata } from 'next'
import Navbar from '@/components/client/Navbar'
import ListMenu from '@/components/client/Menu'
import Body from '@/components/client/Body'
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarHeader,
  SidebarInset,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar'
import { FolderGit2, Newspaper } from 'lucide-react'
import ArrayMap from '@/components/ArrayMap'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayoutAdmin({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const menu = [
    {
      id: '0',
      title: 'Category',
      href: '/admin/category',
      icon: () => <FolderGit2 />,
    },
    {
      id: '1',
      title: 'Article',
      href: '/admin/article',
      icon: () => <Newspaper />,
    },
  ]

  return (
    <Body>
      <SidebarProvider>
        <Sidebar>
          <SidebarHeader />
          <SidebarContent>
            <SidebarGroupContent>
              <SidebarMenu>
                <ArrayMap
                  of={menu}
                  render={(item, index) => (
                    <SidebarMenuItem key={item.title}>
                      <SidebarMenuButton asChild>
                        <a href={item.href}>
                          <item.icon />
                          <span>{item.title}</span>
                        </a>
                      </SidebarMenuButton>
                    </SidebarMenuItem>
                  )}
                />
              </SidebarMenu>
            </SidebarGroupContent>
            <SidebarGroup />
          </SidebarContent>
        </Sidebar>
        <main className="flex-1 flex flex-col min-w-0 overflow-hidden">
          <div className="p-2">
            <SidebarTrigger />
          </div>
          <hr className="-ml-5 -mr-5" />
          <div className=" flex-1 p-5">{children}</div>
        </main>
      </SidebarProvider>
    </Body>
  )
}
