import type { Metadata } from 'next'
import Navbar from '@/components/client/Navbar'
import ListMenu from '@/components/client/Menu'
import Body from '@/components/client/Body'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayoutAdmin({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Body>
      <Navbar />
      <div
        id="sidebar_menu"
        className="grid grid-cols-[255px_1fr] h-[calc(100vh-56px)] duration-300 ease-in-out"
      >
        <div className="w-full">
          <ListMenu />
        </div>
        <div className="h-full w-full bg-white border-l-2 border-gray-200 relative z-10 p-5 overflow-auto dark:bg-black dark:shadow-white dark:shadow-lg dark:border-white">
          <div className="shadow-md p-5 rounded-lg">{children}</div>
        </div>
      </div>
    </Body>
  )
}
